loki:
  storage:
    bucketNames:
      chunks: ogtshv-bucket
      ruler: ogtshv-bucket
      admin: ogtshv-bucket
    type: 's3'
    s3:
      endpoint: storage.yandexcloud.net
      secretAccessKey: YCNk3DFoil0-P3FlUEG1ZlUHnUWxXn9f9d9uAu6o
      accessKeyId: YCAJEu4R4IuWKe8AKy8CIt-ed
  auth_enabled: false
  commonConfig:
    replication_factor: 1

test:
  enabled: false

monitoring:
  selfMonitoring:
    enabled: false
    grafanaAgent:
      installOperator: false
  lokiCanary:
    nodeSelector:
      infra: "true"
    tolerations:
      - key: "node-role"        
        operator: "Equal"
        value: "infra"        
        effect: "NoSchedule"

singleBinary:
  replicas: 1
  nodeSelector:
    infra: "true"
  tolerations:
    - key: "node-role"        
      operator: "Equal"
      value: "infra"        
      effect: "NoSchedule"

gateway:
  nodeSelector:
    infra: "true"
  tolerations:
    - key: "node-role"        
      operator: "Equal"
      value: "infra"        
      effect: "NoSchedule"