config:
  # publish data to loki
  clients:
    - url: http://loki-gateway/loki/api/v1/push
      tenant_id: 1
tolerations:
  - key: "node-role"        
    operator: "Equal"
    value: "infra"        
    effect: "NoSchedule"