stages:
  - module-pipelines

app:
  stage: module-pipelines
  trigger:
    include:
      - "/app/.gitlab-ci.yml"
    strategy: depend #depend нужен, если какой-нибудь дочерний пайплайн свалился, мы знали, что общий пайплайн тоже идёт с ошибкой
  only:
    changes: #как только происходит изменение в папке app, запускается дочерний пайплайн, который лежит в этой папке
      - app/**/*

infra:
  stage: module-pipelines
  trigger:
    include:
      - "/infra/.gitlab-ci.yml"
    strategy: depend #depend нужен, если какой-нибудь дочерний пайплайн свалился, мы знали, что общий пайплайн тоже идёт с ошибкой
  only:
    changes:  #как только происходит изменение в папке infra, запускается дочерний пайплайн, который лежит в этой папке
      - infra/**/*

tools:
  stage: module-pipelines
  trigger:
    include:
      - "/tools/.gitlab-ci.yml"
    strategy: depend #depend нужен, если какой-нибудь дочерний пайплайн свалился, мы знали, что общий пайплайн тоже идёт с ошибкой
  only:
    changes:  #как только происходит изменение в папке tools, запускается дочерний пайплайн, который лежит в этой папке
      - tools/**/*
